# GET request to retrieve all questions for all exams
# GET http://localhost:8080/exam-question

POST http://localhost:8080/exam-question
Content-Type: application/json

{
    "examName": "examName",
    "questionText": "What is the capital of France?",
    "correctAnswer": 1,
    "questionValue": 100,
    "option1": 1,
    "option2": 2,
    "option3": 3,
    "option4": 4
}