# GET request to retrieve all exams
GET http://localhost:8080/exams

# POST request to create an exam
POST http://localhost:8080/exams
Content-Type: application/json

{
    "examName": "examName",
    "examCourseName": "courseName",
    "examTopic": "examTopic",
    "examDateBogotaTimezone": "2021-01-01T00:00:00",
}