# GET request to retrieve all students
# GET http://localhost:8080/student

# POST request to create a new student
POST http://localhost:8080/student
Content-Type: application/json

    {
    "studentName": "John Doe",
    "studentAge": 18,
    "studentCity": "Paris",
    "studentTimezone": "Europe/Paris"
    }